DROP TABLE IF EXISTS invoice;
DROP TABLE IF EXISTS invoice_item;
DROP TABLE IF EXISTS products;

/*DROP TABLE IF EXISTS customer_order;
DROP TABLE IF EXISTS cancellation_invoice;
DROP TABLE IF EXISTS invoice_item;
DROP TABLE IF EXISTS invoice;
DROP TABLE IF EXISTS promotion;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS tax;
DROP TABLE IF EXISTS operator;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS address;
DROP TYPE IF EXISTS permissions_type;
*/